name: Build and Test ASP.NET Core API

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '9.0.x'

    - name: Restore dependencies
      run: dotnet restore ./src/PS.WeatherLite/PS.WeatherLite.Web/PS.WeatherLite.Web.csproj

    - name: Build
      run: dotnet build ./src/PS.WeatherLite/PS.WeatherLite.Web/PS.WeatherLite.Web.csproj --no-restore --configuration Release
