name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '9.0'

    - name: Restore dependencies
      run: dotnet restore D:\Repositories\GitHub\WeatherLite\src\PS.WeatherLite\PS.WeatherLite.Web

    - name: Build solution
      run: dotnet build D:\Repositories\GitHub\WeatherLite\src\PS.WeatherLite\PS.WeatherLite.Web --no-restore --configuration Release

    - name: Run tests
      run: dotnet test D:\Repositories\GitHub\WeatherLite\src\PS.WeatherLite\PS.WeatherLite.Web --no-build --verbosity normal
